### ISSUE TITLE
IndexError when trying to sample from fine-tuned model

### ISSUE THREAD

**Issue by ignaciocearuiz** [hugohrban/ProGen2-finetuning#8]
Hi! Here's a breakdown of my setup and the issue:

### Setup

- **Environment**: Google Colab Pro (NVIDIA A100 40GB GPU)
- **Steps I followed**:
  1. Cloned the repo and ran `!pip install -r requirements.txt`.
  2. Ran `!python ProGen2-finetuning/src/download_pfam.py PF02680` to get one of the example families to fine-tune.
  3. Prepared the dataset with the `prepare_data.py` script using the parameters instructed in the Readme, but without the `--bidirectional` flag.
  4. Successfully executed `!python ProGen2-finetuning/src/finetune.py` to fine-tune the `progen2-small` model with the train and test data files generated in the previous step.
  5. Ran the sample script over the fine-tuned model with the next parameters:
    ```bash
    python ProGen2-finetuning/src/sample.py \
        --model=checkpoints/progen2-small-finetuned/e5/ \
        --device=cuda \
        --batch_size=4 \
        --iters=1 \
        --max_length=512 \
        --t=1.0 \
        --k=10 \
        --prompt="<|pf02680|>1"
    ```

### Issue Description

While running the sample script, this was the output:

```
INFO: Device: cuda
INFO: Loading model from checkpoints/progen2-small-finetuned/e5/
INFO: Loading tokenizer
INFO: Prompt tokens: ['<|pf02680|>', '1']
INFO: Sampling batch 1 / 1
100% 510/510 [00:10<00:00, 49.14it/s]
Traceback (most recent call last):
  File "/content/ProGen2-finetuning/src/sample.py", line 266, in <module>
    main(args)
  File "/content/ProGen2-finetuning/src/sample.py", line 207, in main
    c = truncate(c)
  File "/content/ProGen2-finetuning/src/sample.py", line 84, in truncate
    terminus = seq[0]
IndexError: string index out of range
```

I tried executing the same steps inside a venv in the Colab Pro Terminal as instructed in the Readme, but got the same error. Then, when inspecting the output file, no sequences are printed there, as expected when analyzing the lines of code that raise the error.

Can someone provide guidance on how to proceed? Thanks in advance!

**Comment by xianyu-123** [comment]
i have the same issue, did you solved it?
I used this method and it seems like the problem has been solved，sample.py line 206:
`
for j, c in enumerate(samples):
      print(f">seq_{i * args.batch_size + j}", file=f)
     try:
          c = truncate(c)
          print(c, file=f)
      except:
          print(c,"****")
`

**Comment by ignaciocearuiz** [comment]
Hi! Thanks, but that method didn't work out for me :(

I edited the sample.py script as you mentioned, which allowed the treatment of the IndexError exception, but still not getting sequences. I got this output:

```
INFO: Device: cuda
INFO: Loading model from checkpoints/progen2-small-finetuned/e5/
INFO: Loading tokenizer
INFO: Prompt tokens: ['<|pf02680|>', '1']
INFO: Sampling batch 1 / 1
100% 510/510 [00:10<00:00, 49.34it/s]
<|pf02680|>1<|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|> ****
<|pf02680|>1211QNR2EQ2TP2NFTQ22PWF2PPP2Q2KW2QTT222IW2EVI2R2KI2TI2P22EK222TK2E2KWWWIE22<|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|><|pf02680|> ****
INFO: Generated samples were saved to file generated_samples/samples_ctx<|pf02680|>1_k10_t1.0.fa
INFO: Sampling finished.
```

Then, the contents of the output file were:

```
>seq_0
>seq_1
>seq_2
K
>seq_3


```

**Comment by xianyu-123** [comment]
您好，您的来信我已经收到，感谢您的来信!谢谢

**Comment by ignaciocearuiz** [comment]
Hello! I found a turnaround for this issue. I was able to generate sequences by means of loading the fine-tuned model directly and discarding the `truncate` function at all. I also had to change my prompt to `<|my_tag|>1M`, given that if I didn't include the `M` amino acid, the model didn't generate anything useful. 

My solution (includes the use of a regex in order to extract the AA sequence from a correctly generated sequence):

```python
from transformers import AutoModelForCausalLM
from tokenizers import Tokenizer
import torch
import re

def load_local_progen2(model_path, tokenizer_path):
    """
    Load a local ProGen2 model and tokenizer.

    Args:
        model_path (str): Path to the local ProGen2 model.
        tokenizer_path (str): Path to the local tokenizer.

    Returns:
        model: The loaded ProGen2 model.
        tokenizer: The loaded tokenizer.
    """
    model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True)
    tokenizer = Tokenizer.from_file(tokenizer_path)
    tokenizer.no_padding()
    return model, tokenizer

# Define paths to the local model and tokenizer
local_model_path = "checkpoints/progen2-medium-finetuned/e5"
local_tokenizer_path = "checkpoints/progen2-medium-finetuned/e5/tokenizer.json"

# Load model and tokenizer
model, tokenizer = load_local_progen2(local_model_path, local_tokenizer_path)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Prepare input
prompt = "<|my_tag|>1M"
input_ids = torch.tensor([tokenizer.encode(prompt).ids], device=device)
pattern = re.compile(r"^<\|my_tag\|>1(M[A-Z]+)2?")

# Generate sequences
output_sequences = model.generate(
    input_ids=input_ids,
    max_length=1024,  
    num_return_sequences=25,  
    do_sample=True,  
    temperature=1.0,  
    top_k=15
)

output_file = "final_sequences.fasta"
with open(output_file, "w") as f:
    for idx, sequence in enumerate(output_sequences):
        generated_ids = sequence.cpu().numpy().tolist()
        generated_sequence = tokenizer.decode(generated_ids)

        if not pattern.match(generated_sequence):
            print(generated_sequence)
            continue

        match = pattern.search(generated_sequence)
        truncated_sequence = match.group(1)
        f.write(f">seq_{idx}\n{truncated_sequence}\n")
```

Any further comment would be much appreciated 🙌🏻, but I would consider this as closed.

**Comment by xianyu-123** [comment]
您好，您的来信我已经收到，感谢您的来信!谢谢
